
# Name of the pack
name: LAMP stack

# Description of the pack
description: |+
  This LAMP pack references the Linux, Apache, MySQL and PHP observability pack.
  It includes a specific dashboard to get observability for an entire LAMP stack.
  
# Support level
level: New Relic

# Authors of the quickstart
authors:
  - Stijn Polfliet

# References to other packs (optional)
# References are grouped by the type: operating-system, database, webserver, queue, ..
# The reference under the type is a at least one system, so at least one operating-system, database, ..
references:
  - type: os
    name: linux
  - type: webserver
    name: apache
  - type: database
    name: mysql  
  - type: apm
    name: php