# Name of the pack
name: PHP

# Description of the pack
description: |+
  This is an observability pack for PHP applications.
  This pack relies on the New Relic PHP agent, with distributed tracing enabled (https://docs.newrelic.com/docs/agents/php-agent/features/distributed-tracing-php-agent/)

# Support level: New Relic | Verified | Community
level: New Relic

# Design
logo: logo.jpg
website: https://www.php.net/

# Authors of the pack
authors:
  - Stijn Polfliet

# Instrumentation (optional)
# This allows you to define which instrumentation is needed for your pack
# Any file in the instrumentation folder will automatically be picked up
instrumentation:
  - type: apm
    name: php